name: Build check

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build check
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Build solution
      run: dotnet build STB-DiffChecker.sln -c ${{ matrix.configuration }}
